"""add mietzahlungen

Revision ID: ee08c07e7d94
Revises: 7be9923aff95
Create Date: 2024-09-04 11:42:06.572470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee08c07e7d94'
down_revision: Union[str, None] = '7be9923aff95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mietzahlungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monat', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mietzahlungen')
    # ### end Alembic commands ###
