MIETE = 213.61
KAFFEEPREIS_GAST = 1.0
BANKVERBINDUNG = "Nicole Reichheim, IBAN: DE90 8605 5592 1800 4837 80"

[connections.coffee_counter]
host = "162.55.213.63"
port = 3306
username = "streamlit_arbeitsplatz"
password = "Arb_platz_57"
database = "coffee_test"
dialect = "mysql"
driver = "pymysql"

[smtp]
port = 587
server = "mail.your-server.de"
login = "lsbkaffee@andrewendler.de"
password = "C6gn73j5D8wE4d2U"
sender_email = "lsbkaffee@andrewendler.de"
reply_email = "andre.wendler@leipzig.de"

[admins]
rechnung = 'Nicole Reichheim'
technik = 'André Wendler'
